name: Trigger auto deployment for streamlit-helloworld

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/streamlit-helloworld-AutoDeployTrigger-4fcf9742-2594-4dd9-ab1c-a2949a2ef401.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STREAMLITHELLOWORLD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STREAMLITHELLOWORLD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STREAMLITHELLOWORLD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: ${{ secrets.STREAMLITHELLOWORLD_REGISTRY_URL }}
          registryUsername: ${{ secrets.STREAMLITHELLOWORLD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STREAMLITHELLOWORLD_REGISTRY_PASSWORD }}
          containerAppName: streamlit-helloworld
          resourceGroup: myResourceGroup
          imageToBuild: streamlit-helloworld:${{ github.sha }}


